cars/urls.py
from django.urls import path

from cars.views import ShowCarsView, ShowCarDetailView, CarFilterView


app_name = 'cars'
urlpatterns = [
    path('cars/', ShowCarsView.as_view(), name='all_cars'),
    path('cars/filter', CarFilterView.as_view(), name='filter_cars'),
    path('cars_detail/<int:pk>', ShowCarDetailView.as_view(), name='car_detail'),

]

reservations/urls.py
from django.urls import path

from reservations.views import ReservationListView, ReservationDetailView, ReservationUpdateView, \
    ReservationDeleteView, CreateReservationView, FinishReservationWithFilters

app_name = 'reservations'

urlpatterns = [
    path('create_reservation/', CreateReservationView.as_view(), name='create_reservation'),
    path('your_reservations/', ReservationListView.as_view(), name='your_reservations'),
    path('your_reservation_detail/<int:pk>', ReservationDetailView.as_view(), name='reservation_detail'),
    path('edit_reservation/<int:pk>', ReservationUpdateView.as_view(), name='edit_reservation'),
    path('delete_reservation/<int:pk>', ReservationDeleteView.as_view(), name='delete_reservation'),
    path('finish_reservation/<int:pk>', FinishReservationWithFilters.as_view(), name='finish_reservation'),
]

wypozyczalnia_aut/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('', include('reservations.urls')),
    path('', include('accounts.urls')),
    path('', include('Base_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/models.py
from django.contrib.auth.models import User
from django.db import models

from cars.models import Car


# Create your models here.


class Reservation(models.Model):
    reservation_start_date = models.DateField()
    reservation_end_date = models.DateField()
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='car_reservation', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_reservation')

reservations/forms.py
from django.forms import ModelForm, Form
from django import forms

from cars.models import Car
from reservations.models import Reservation


class CreateReservationForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ['reservation_start_date', 'reservation_end_date']

        widgets = {
            'reservation_start_date': forms.DateInput(attrs={'type': 'date'}),
            'reservation_end_date': forms.DateInput(attrs={'type': 'date'}),
        }

reservations/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from cars.forms import CarFilterForm
from cars.models import Car, CarClass
from reservations.forms import CreateReservationForm

from reservations.models import Reservation


def user_is_reservation_owner(function):
    def wrap(request, *args, **kwargs):
        reservation = Reservation.objects.get(pk=kwargs['pk'])
        if reservation.user == request.user:
            return function(request, *args, **kwargs)
        else:
            raise Http404("Brak dostępu do rezerwacji")

    return wrap


# Create your views here.
@method_decorator(login_required, name='dispatch')
class CreateReservationView(CreateView):
    model = Reservation
    form_class = CreateReservationForm
    template_name = 'reservations/create_reservation_form.html'
    context_object_name = 'form'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = request.user
            reservation = form.save(commit=False)
            if reservation.reservation_start_date < timezone.now().date() or \
                    reservation.reservation_end_date < timezone.now().date() or \
                    reservation.reservation_start_date > reservation.reservation_end_date:
                error = "Podana Data Jest nieprawidlowa"
                return render(request, self.template_name, {'form': form, 'error': error})
            reservation.user = user
            reservation.save()
            return redirect('reservations:finish_reservation', reservation.id)
        return render(request, self.template_name, {'form': form})


@method_decorator(login_required, name='dispatch')
class ReservationListView(ListView):
    model = Reservation
    template_name = 'reservations/all_reservations.html'
    context_object_name = 'reservations'

    def get(self, request, *args, **kwargs):
        reservations = Reservation.objects.filter(user=request.user)
        context = {'reservations': reservations}
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_reservation_owner, name='dispatch')
class ReservationDetailView(DetailView):
    model = Reservation
    template_name = 'reservations/reservations_detail.html'
    context_object_name = 'reservation'


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_reservation_owner, name='dispatch')
class ReservationUpdateView(UpdateView):
    model = Reservation
    form_class = CreateReservationForm
    template_name = 'reservations/create_reservation_form.html'
    context_object_name = 'form'

    def post(self, request, *args, **kwargs):
        instance = self.get_object()

        form = self.form_class(request.POST, instance=instance)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.car = None
            if reservation.reservation_start_date < timezone.now().date() or \
                    reservation.reservation_end_date < timezone.now().date() or \
                    reservation.reservation_start_date > reservation.reservation_end_date:
                error = "Podana Data Jest nieprawidlowa"
                return render(request, self.template_name, {'form': form, 'error': error})
            reservation.save()
            return redirect('reservations:finish_reservation', pk=reservation.id)
        return render(request, self.template_name, {'form': form})


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_reservation_owner, name='dispatch')
class ReservationDeleteView(DeleteView):
    model = Reservation
    template_name = 'reservations/delete_reservation_form.html'
    context_object_name = 'reservation'
    success_url = reverse_lazy('reservations:your_reservations')


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_reservation_owner, name='dispatch')
class FinishReservationWithFilters(UpdateView):
    model = Reservation
    template_name = 'reservations/finish_reservation.html'

    def get(self, request, *args, **kwargs):
        reservation = self.get_object()
        reservation_start_date = reservation.reservation_start_date
        reservation_end_date = reservation.reservation_end_date

        available_cars = Car.objects.exclude(
            car_reservation__reservation_start_date__lte=reservation_end_date,
            car_reservation__reservation_end_date__gte=reservation_start_date)
        form = CarFilterForm(request.GET)

        if form.is_valid():
            model = form.cleaned_data.get('model')
            if model:
                available_cars = available_cars.filter(model=model)

            fuel = form.cleaned_data.get('fuel')
            if fuel:
                available_cars = available_cars.filter(fuel=fuel)

            engine_size = form.cleaned_data.get('engine_size')
            if engine_size:
                available_cars = available_cars.filter(engine_size=engine_size)

            color = form.cleaned_data.get('color')
            if color:
                available_cars = available_cars.filter(color=color)

            car_class = form.cleaned_data.get('car_class')
            if car_class:
                available_cars = available_cars.filter(model__car_class__in=car_class)
        car_classes = CarClass.objects.filter(
            id__in=available_cars.values_list('model__car_class', flat=True)).distinct()

        context = {'reservation': reservation, 'available_cars': available_cars, 'car_classes': car_classes,
                   'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        reservation = self.get_object()
        selected_car_id = request.POST.get('selected_car')
        if selected_car_id:
            selected_car = Car.objects.get(id=selected_car_id)
            reservation.car = selected_car
            reservation.save()
            return redirect('reservations:your_reservations')
        else:
            reservation.delete()
            return redirect('reservations:your_reservations')

reservations/templates/reservations/all_reservations.html
{% extends 'Base_app/base.html' %}
{% load static %}
{% block content %}
<div class="car-container-title"><h2>Twoje rezerwacje</h2></div>
<div class="reservation-table">
    <table>
        <thead>
        <tr>
            <td>LP</td>
            <td>Samochód</td>
            <td>Data początkowa</td>
            <td>Data końcowa</td>
            <td>Operacje</td>
        </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
        <tr>
            <td>{{ reservation.id }}</td>
            <td><a href="{% url 'cars:car_detail' reservation.car.id %}">{{ reservation.car }}</a></td>
            <td>{{ reservation.reservation_start_date }}</td>
            <td>{{ reservation.reservation_end_date }}</td>
            <td>
                <p><a href="{% url 'reservations:edit_reservation' reservation.id %}">
                    <button>Zmień datę</button>
                </a></p>
                <p><a href="{% url 'reservations:delete_reservation' reservation.id %}">
                    <button>Anuluj rezerwację</button>
                </a></p>
            </td>
        </tr>

        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

reservations/templates/reservations/create_reservation_form.html
{% extends 'Base_app/base.html' %}
{% block content %}
{% if error %}
<p>{{error}}</p>
{% endif %}
<form method="POST"  class="reservation-form">
    {% csrf_token %}
    <label for="pickup-date">Data Odbioru:</label>
    {{ form.reservation_start_date }}


    <label for="return-date">Data Zwrotu:</label>
    {{ form.reservation_end_date }}
    <button type="submit">ADD reservation</button>

</form>
{% endblock %}

reservations/templates/reservations/delete_reservation_form.html
{% extends 'Base_app/base.html' %}

{% block content %}
<h2>Confirm Delete</h2>
<p>Do you really want to delete "{{ object }}"?</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>
<a href="{% url 'reservations:reservation_detail' object.id %}">Cancel</a>

{% endblock %}

reservations/templates/reservations/finish_reservation.html
{% extends 'Base_app/base.html' %}
{% load static %}
{% block content %}
<form method="get" action="{% url 'reservations:finish_reservation' reservation.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Fileter</button>
</form>

<h1>Wybierz samochód do kontynuacji rezerwacji</h1>

<form method="post">
    {% csrf_token %}
    {% for car_class in car_classes %}
    <div><h2>Klasa {{ car_class }}</h2></div>
    <div class="class-container">
        {% for car in available_cars %}
        {% if car.model.car_class == car_class %}
        <div class="widget-car">
            <div class="car-image">
                {% if car.pic %}
                <img src="{{ car.pic.url }}" alt="Jedziesz jak gość!" width="330">
                {% else %}
                <img src="{% static 'img/photographer.png' %}" alt="Zara Zosia zrobi" width="330">
                {% endif %}
            </div>
            <div class="car-details">
                <h2>{{ car.model }}</h2>
                <h2>{{ car.color.color_name }}</h2>
                <p>Silnik: {{ car.engine_size }} {{ car.fuel }}</p>
                <p>Klasa: {{ car.model.car_class }}</p>
                <p>Dostępność: </p>
                <input type="radio" id="car_{{ car.id }}" name="selected_car" value="{{ car.id }}">
                <label for="car_{{ car.id }}">{{ car }}</label><br>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>

    {% endfor %}
    <button type="submit">Zarezerwuj samochód</button>
</form>


{% endblock %}

reservations/templates/reservations/reservations_detail.html
{% extends 'Base_app/base.html' %}


{% block content %}
<body>
{{ reservation }}

<a href="{% url 'reservations:edit_reservation' reservation.id %}">Update</a>
<a href="{% url 'reservations:delete_reservation' reservation.id %}">Delete</a>


{% endblock %}