Base_app/urls.py
from django.urls import path

from Base_app.views import main_view
from cars.views import my_view
from cars.views import ShowCarsView, ShowCarDetailView

app_name = 'Base_app'
urlpatterns = [
    path('', main_view, name='main')
]

accounts/urls.py
from django.urls import path
from accounts.views import MyLoginView, MySignUpView
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('registration/', MySignUpView.as_view(), name='register_user'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

cars/urls.py
from django.urls import path

from cars.views import ShowCarsView, ShowCarDetailView, CarFilterView


app_name = 'cars'
urlpatterns = [
    path('cars/', ShowCarsView.as_view(), name='all_cars'),
    path('cars/filter', CarFilterView.as_view(), name='filter_cars'),
    path('cars_detail/<int:pk>', ShowCarDetailView.as_view(), name='car_detail'),

]

reservations/urls.py
from django.urls import path

from reservations.views import ReservationListView, ReservationDetailView, ReservationUpdateView, \
    ReservationDeleteView, CreateReservationView, FinishReservationWithFilters

app_name = 'reservations'

urlpatterns = [
    path('create_reservation/', CreateReservationView.as_view(), name='create_reservation'),
    path('your_reservations/', ReservationListView.as_view(), name='your_reservations'),
    path('your_reservation_detail/<int:pk>', ReservationDetailView.as_view(), name='reservation_detail'),
    path('edit_reservation/<int:pk>', ReservationUpdateView.as_view(), name='edit_reservation'),
    path('delete_reservation/<int:pk>', ReservationDeleteView.as_view(), name='delete_reservation'),
    path('finish_reservation/<int:pk>', FinishReservationWithFilters.as_view(), name='finish_reservation'),
]

wypozyczalnia_aut/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('', include('reservations.urls')),
    path('', include('accounts.urls')),
    path('', include('Base_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Base_app/views.py
from django.shortcuts import render

from accounts.forms import MyLoginForm
from cars.models import Car
from reservations.forms import CreateReservationForm
from reservations.views import CreateReservationView

# Create your views here.
import random


def main_view(request):
    form = CreateReservationForm
    cars = Car.objects.all()
    login_form = MyLoginForm
    random_cars = random.sample(list(cars), 3)
    return render(request, 'Base_app/main.html',
                  {'form': form, 'cars': cars, 'login_form': login_form, 'random_cars': random_cars})

Base_app/templates/Base_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <title>Wypożyczalnia Samochodów</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Ops+One&family=Inter:wght@100..900&family=Montserrat:ital,wght@1,100&display=swap"
          rel="stylesheet">
</head>
<body>
<div class="container">
    <header>
        <!--    <h1>Wypożyczalnia Samochodów</h1>
        -->
        <img src="{% static 'img/logo.png' %}" width="800" height="140">
        <nav>
            <ul>
                <li><a href="{% url 'Base_app:main' %}">Strona Główna</a></li>
                <!--<li><a href="{% url 'cars:all_cars' %}">Oferta</a></li>-->>
                <li><a href="{% url 'cars:filter_cars' %}">Znajdź pojazd</a></li>
                <li><a href="#">Kontakt</a></li>
                {% if user.is_authenticated %}

                <li><a href="{% url 'reservations:create_reservation' %}">Zarezerwuj pojazd</a></li>
                <li><a href="{% url 'reservations:your_reservations' %}">Moje rezerwacje</a></li>
                <li><form style="display:inline" action="{% url 'accounts:logout' %}" method="POST">{% csrf_token %}<input type="submit" value="Wyloguj">
                    </form> </li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Zaloguj</a></li>
                <li><a href="{% url 'accounts:register_user' %}">Stwórz konto</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    {% block content %}{% endblock %}

    <footer>
        <div class="footer-content">
            <div class="company-info">
                <h3>HS Car Shere Sp z łoło</h3>
                <p>ul. Złota 44</p>
                <p>00-120 Warszawa</p>
                <p>NIP PL: 555 111 22 22</p>
                <p>REGON: 123456789</p>
                <p>@: <a href="mailto:biuro@hscarshare.com">biuro@hscarshare.com</a></p>
                <!-- to możemy też napisać jako zgłoszenie napisania formularza na emel-->
            </div>
            <div class="callcenter">
                <h3>Całodobowe 24/7 Callcenter</h3>
                <p><img src="{% static 'img/callcenter.jpeg' %}" width="300"></p>
                <p>0-700-789-789</p>
                <p>Koszt połączenia zależnie od operatora</p>
            </div>
            <div class="widgetboxes">
                <div class="widgetbox-title">
                    <strong>Obsługa rezerwacji long</strong>
                    <p><a href="mailto:rezerwacja@hscarshare.com" title="rezerwacja@hscarshare.com">rezerwacja@carshare.com</a></p>
                </div>
                <div class="widgetbox">
                    <strong>Obsługa rezerwacji</strong>
                    <p><a href="mailto:rezerwacja@hscarshare.com" title="rezerwacja@hscarshare.com">rezerwacja@carshare.com</a></p>
                </div>
                <div class="widgetbox">
                    <strong>Obsługa rezerwacji 2</strong>
                    <p><a href="mailto:rezerwacja@hscarshare.com" title="rezerwacja@hscarshare.com">rezerwacja@carshare.com</a></p>
                </div>
                <div class="widgetbox">
                    <strong>Obsługa rezerwacji 3</strong>
                    <p><a href="mailto:rezerwacja@hscarshare.com" title="rezerwacja@hscarshare.com">rezerwacja@carshare.com</a></p>
                </div>
                <div class="widgetbox">
                    <strong>Obsługa rezerwacji 4</strong>
                    <p></p><a href="mailto:rezerwacja@hscarshare.com" title="rezerwacja@hscarshare.com">rezerwacja@carshare.com</a></p>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            &copy; 2024 HS Car Share. Wszelkie prawa zastrzeżone i pamiętaj... wsiadasz i jedziesz jak Gość!
        </div>
    </footer>
</div>
</body>
</html>

Base_app/templates/Base_app/main.html
{% extends 'Base_app/base.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}

<section class="reservation-section">
    <div class="car-container-title"><h2>Rezerwacja Samochodu</h2></div>
    <form action="{% url 'reservations:create_reservation' %}" method="post" class="reservation-form">
        {% csrf_token %}
        <label for="pickup-date">Data Odbioru:</label>
        {{ form.reservation_start_date }}
        <label for="return-date">Data Zwrotu:</label>
        {{ form.reservation_end_date }}
        <button type="submit">Zarezerwuj Samochód</button>
    </form>
</section>
{% else %}
<section class="reservation-section">
    <div class="car-container-title"><h2>Zaloguj by zlozyc rejestracje</h2></div>
    <form action="{% url 'accounts:login' %}" method="post" class="reservation-form">
        {% csrf_token %}
        <label for="pickup-date">Login:</label>
        {{ login_form.username }}


        <label for="return-date">Password:</label>
        {{ login_form.password }}

        <button type="submit">Login</button>
    </form>
</section>
{% endif %}
<div class="car-container-title"><h2>Polecane samochody</h2></div>
<div class="car-container">
    {% for car in random_cars %}
        <div class="widget-car">
            <div class="car-image">
                {% if car.pic %}
                    <img src="{{ car.pic.url }}" alt="Jedziesz jak gość!" width="330">
                {% else %}
                    <img src="{% static 'img/photographer.png' %}" alt="Zara Zosia zrobi" width="330">
                {% endif %}
            </div>
            <div class="car-details">
                <h2>{{ car.model }}</h2>
                <h2>{{ car.color.color_name }}</h2>
                <p>Silnik: {{ car.engine_size }} {{ car.fuel }}</p>
                <p>Cena: {{ car.model.car_class.price }} PLN/24</p>
                <p align="center"><button type="submit"><a href="{% url 'cars:car_detail' car.id %}">Sprawdź szczegóły</a></button>
            </div>
        </div>
    {% endfor %}
</div>
<section class="map">
    <div class="car-container-title">
        <h2>Nasza lokalizacja</h2></div>
    <div class="googlemap">
    <p>Jeżeli nie jesteś blisko - nie martw się! Przywozimy nasze samochody do Klienta!</p>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d610.9180962726817!2d21.00173376971237!3d52.23116969824918!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ecc8c49633d1d%3A0xaa349f21569c205!2sTower%2C%20Z%C5%82ota%2044%2C%20Z%C5%82ota%2044%2C%2000-120%20Warszawa!5e0!3m2!1spl!2spl!4v1707072645256!5m2!1spl!2spl" width="800" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div></section>

{% endblock %}